### PR TITLE
Create LICENCE

### PR DESCRIPTION
**Pull request by ronaldburns**
Having no license doesn't allow creators to continue your project.
The MIT licence will allow the plugin to be kept alive by other developers while still giving you credit.
https://choosealicense.com/no-permission/

https://github.com/rojo8399/AdventureMMO

### CODE REVIEW

**Comment by parlough** [comment]
There's other licenses to choose as well if you'd prefer different terms. That [choose a license](https://choosealicense.com/) site has a lot of great information for you to browse to choose one.

**Comment by Seathre** [comment]
@Daniel12321 If this project has been abandoned, could you please license it for other people to pick it up and continue work? There's still plenty of folks who use this plugin, we'd really appreciate it if you did this.

**Comment by Guite-Emortal** [comment]
@Daniel12321 If this project has been abandoned, could you please license it for other people to continue where you left off. I'd very much like to take a crack at furthering this project.

**Comment by MadHalaster** [comment]
Thanks so much Daniel.

**Pull request merged**
